version: '3.8'

services:
  # backend_node_dev:
  #   build: ../Backend/Test-Backend  # Path to backend repository
  #   docker-compose: ../Backend/Test-Backend/docker-compose.dev.yml

  # frontend_next_dev:
  #   build: ../Frontend/Test-Frontend/test-frotnend  # Path to frontend repository
  #   docker-compose: ../Frontend/Test-Frontend/test-frotnend/docker-compose.dev.yml

  nginx:
    image: nitinsaa1999/testproject-nginx_dev
    container_name: nitin_nginx_dev
    build:
      context: ./
      dockerfile: DockerfileDev
    volumes:
      - D:\Test Project\proxyServer:/app
    # depends_on:
    #   - frontend_next_dev
    #   - backend_node_dev
    environment:
      NODE_ENV: development
    ports:
      - 10000:80
    restart: unless-stopped
    command: sleep infinity
    networks:
      - node-network
networks: 
  node-network:
    external: true

